on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        required: true
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
      - cloudpod_workflow # TODO remove
            
permissions:
  contents: write

name: Create Release
jobs:
  build:
    strategy:
      matrix:
        database-type: [mysql, mariadb]
    uses: ./.github/workflows/setup.yml
    secrets: inherit
    with:
      store-cloudpod: "true"
      database-type: ${{ matrix.database-type }}
      localstack-version: ${{ inputs.release-tag || 'latest'}}
  upload:
    needs: build
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Download Pod Artifacts
        uses: actions/download-artifact@v3
        with:
          name: cloudpod
      - name: Display structure of downloaded files
        run: ls -R
      - name: Prepare Release.txt
        run: |
          echo "Cloud Pod of the Sample created with LocalStack Version ${{ inputs.release-tag || 'latest'}}." > Release.txt
          echo " * Please use the 'release-pod-{database}.zip' you need for your configuration." >> Release.txt
          echo " * By default LocalStack uses the engine 'mariadb', so you need 'release-pod-mariadb.zip' " >> Release.txt
          echo "   * Click here to inject the 'mariadb' pod into your running LocalStack instance: [![LocalStack Pods Launchpad](https://localstack.cloud/gh/launch-pod-badge.svg)](https://app.localstack.cloud/launchpad?url=https://github.com/$GITHUB_REPOSITORY/releases/download/${{ inputs.release-tag || 'latest'}}/release-pod-mariadb.zip)" >> Release.txt
          echo " * If you start LocalStack with 'RDS_MYSQL_DOCKER=1', please use the 'mysql' pod ('release-pod-mysql.zip')" >> Release.txt
          echo "   * Click here to inject the 'mysql' pod into your running LocalStack instance: [![LocalStack Pods Launchpad](https://localstack.cloud/gh/launch-pod-badge.svg)](https://app.localstack.cloud/launchpad?url=https://github.com/$GITHUB_REPOSITORY/releases/download/${{ inputs.release-tag || 'latest'}}/release-pod-mysql.zip)" >> Release.txt
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ inputs.release-tag || 'latest'}}"
          name: "Cloud Pod for LocalStack Version '${{ inputs.release-tag || 'latest'}}'"
          body-path: ./Release.txt
          files: |
              ./release-pod-mysql.zip
              ./release-pod-mariadb.zip